from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static

from django.conf import settings


from scrap import views
app_name = "scrap"
urlpatterns = [
    path('classcentral/', views.home_page),
    path('report/free-certificates/', views.report_cer),
    path('report/most-popular-courses-2022/', views.report_2022),
    path('report/most-popular-online-courses/', views.report_pop_cource),
    path('report/best-free-online-courses-2022/', views.report_free_2022),
    path('report/best-free-online-courses-2021/', views.report_free_2021),
    path('report/harvard-cs50-guide/', views.harvard_cs50_guide),
    path('report/report/', views.report),
    path('report/emoocs-2023-cfp/', views.emoocs_2023_cfp),
    path('report/coursera-google-new-deal/', views.coursera_google_new_deal),
    path('report/best-digital-art-courses/', views.best_digital_art_courses),
    path('report/year-in-review/', views.year_in_review),
    path('report/online-learning-deals/', views.online_learning_deals),
    path('report/best-free-online-courses-2021/', views.best_free_online_courses_2021),
    path('report/review-china-economic-transformation/', views.review_china_economic_transformation),
    path('report/free-certificates/', views.free_certificates),
    path('report/best-elm-courses/', views.best_elm_courses),
    path('report/chinese-mooc-platforms/', views.chinese_mooc_platforms),
    path('report/free-google-certifications/', views.free_google_certifications),
    path('report/most-cited-mooc-research/', views.most_cited_mooc_research),
    path('report/coursera-free-online-courses/', views.coursera_free_online_courses),
    path('report/udemy-layoffs/', views.udemy_layoffs),
    path('report/futurelearn-expands-paywall/', views.futurelearn_expands_paywall),
    path('report/best-davinci-resolve-courses/', views.best_davinci_resolve_courses),
    path('report/google-free-certificates/', views.google_free_certificates),
    path('report/udemy-top-courses/', views.udemy_top_courses),
    path('report/most-popular-courses-2023/', views.most_popular_courses_2023),
    path('report/india-online-degrees/', views.india_online_degrees),
    path('report/open-university-insiders-perspective/', views.open_university_insiders_perspective),
    path('report/writing-free-online-courses/', views.writing_free_online_courses),
    path('report/cs50-free-certificate/', views.cs50_free_certificate),
    path('report/edx-top-courses/', views.edx_top_courses),
    path('report/class-central-ddos-attack/', views.class_central_ddos_attack),
    path('report/best-ocaml-courses/', views.best_ocaml_courses),
    path('report/udemy-by-the-numbers/', views.udemy_by_the_numbers),
    path('report/list-of-mooc-based-microcredentials/', views.list_of_mooc_based_microcredentials),
    path('report/linkedin-learning-free-learning-paths/', views.linkedin_learning_free_learning_paths),
    path('report/best-resume-writing-courses/', views.best_resume_writing_courses),
    path('report/coursera-top-courses/', views.coursera_top_courses),
    path('report/mooc-based-masters-degree/', views.mooc_based_masters_degree),

    path('report/author/dhawal/', views.dhawal),
    path('report/author/heba/', views.heba),
    path('report/author/pat-bowden/', views.pat_bowden),
    path('report/author/manoel/', views.manoel),
    path('report/author/ruima/', views.ruima),
    path('collection/ivy-league-moocs/', views.ivy_league_moocs),
    path('collections/', views.collections),
    path('collection/sustainability-online-courses/', views.sustainability_online_courses),
    path('collection/top-free-online-courses/', views.top_free_online_courses),

    path('institution/salesforce/', views.salesforce),
    path('institution/google/', views.google),
    path('institution/smithsonian/', views.smithsonian),
    path('institution/united-nations/', views.united_nations),
    path('institution/ibm/', views.ibm),
    path('institution/british-council/', views.british_council),
    path('institutions/', views.institutions),
    path('institution/linuxfoundation/', views.linuxfoundation),
    path('institution/amazon/', views.amazon),
    path('institution/microsoft/', views.microsoft),

    path('university/mit/', views.mit),
    path('university/stanford/', views.stanford),
    path('university/gatech/', views.gatech),
    path('university/cornell/', views.cornell),
    path('university/purdue/', views.purdue),
    path('university/edinburgh/', views.edinburgh),
    path('university/iitm/', views.iitm),
    path('university/rice/', views.rice),
    path('university/umich/', views.umich),
    path('university/penn/', views.penn),
    path('university/columbia/', views.columbia),
    path('university/duke/', views.duke),
    path('university/harvard/', views.harvard),
    path('universities/', views.universities),
    path('university/iit-kharagpur/', views.iit_kharagpur),

    path('subjects/', views.subjects),
    path('subject/cs/', views.cs),
    path('report/category/best-courses/', views.best_courses),
    path('subject/business/', views.business),

    path('provider/udemy/', views.udemy),
    path('providers/', views.providers),
    path('provider/linkedin-learning/', views.linkedin_learning),
    path('provider/skillshare/', views.skillshare),
    path('provider/edx/', views.edx),
    path('provider/udacity/', views.udacity),
    path('provider/futurelearn/', views.futurelearn),
    path('provider/swayam/', views.swayam),
    path('provider/coursera/', views.coursera),

    path('about/', views.about),
    path('help/', views.help),
    path('signup/', views.signup),
    path('login/', views.login),
    path('contact/', views.contact),
    path('lists/', views.lists),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
